name: ansible

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install ansible
      run: python3 -m pip install --upgrade ansible
    - name: Set ansible password
      run: echo -n "$ANSIBLE_PASSWORD" > .pass
      env:
        ANSIBLE_PASSWORD: ${{ secrets.ANSIBLE_PASSWORD }}
    - name: Set deploy key
      run: echo "$DEPLOY_KEY" > id_rsa
      env:
        DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
    - name: Run ansbile playbooks
      run: ansible-playbook --private-key id_rsa web.yml
