name: ansible

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install ansible
      run: python3 -m pip install --upgrade ansible
    - name: Run ansbile playbooks
      run: ansible-playbook web.yml
